### ISSUE TITLE
Please release jvmci-20.3-b06

### ISSUE THREAD

**Issue by sdeleuze** [graalvm/labs-openjdk-11#12]
Please make a proper release for [jvmci-20.3-b06](https://github.com/graalvm/labs-openjdk-11/releases/tag/jvmci-20.3-b06) since the related artifacts are needed to build GraalVM 20.3.0.

**Comment by dougxc** [comment]
They are now uploaded. Same goes for the 8 and 15 releases of jvmci-20.3-b06. Sorry for the delay.
