### ISSUE TITLE
"Not Found": Tag Release download is broken!

### ISSUE THREAD

**Issue by manuelgustavor3** [graalvm/labs-openjdk-11#15]
e.g. in:
https://github.com/graalvm/labs-openjdk-11/releases/tag/jvmci-21.0-b03

https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-21.0-b03/labsjdk-ce-11.0.9+10-jvmci-21.0-b03-linux-amd64.tar.gz
"Not found"

Please advise,
Manuel

**Comment by dougxc** [comment]
I think this is now fixed - please re-open if problem still exists. cc @ezzarghili

**Comment by manuelgustavor3** [comment]
Thank you very much, I confirm it's working.
