### ISSUE TITLE
BSD support

### ISSUE THREAD

**Issue by Titaniumtown** [graalvm/labs-openjdk-11#16]
Is it possible to add support for the BSDs to be able to build this? A port to the BSDs could be based off of https://github.com/battleblow/openjdk-jdk11u which is openjdk 11 ported for the BSDs, is this possible? I would love to use graalvm on my freebsd server.

**Comment by dougxc** [comment]
While that would indeed be nice, we do not have the resources to maintain a port that deviates much from what is in https://github.com/openjdk/jdk11u-dev.
Your best bet is to try get https://github.com/battleblow/openjdk-jdk11u upstreamed to jdk11u-dev.

**Comment by Titaniumtown** [comment]
Ok, thanks for the info!

**Comment by michael-o** [comment]
@Titaniumtown Were you able to achieve anything? I have no idea what it takes to have GraalVM on top of the regular JDK.

**Comment by Titaniumtown** [comment]
Haven't used BSD in ages now, I wasn't able to get anywhere with this. actually completely forgot about it :p

**Comment by devosalain** [comment]
sdk  list gcn 
returns nothing
uname -a
FreeBSD 14.0-RC3
