### ISSUE TITLE
labsjdk-ce-11-jvmci-21.2-b08 used in GraalVM CE 21.2.0 missing from releases

### ISSUE THREAD

**Issue by zakkak** [graalvm/labs-openjdk-11#17]
Running `mx fetch-jdk` in graal's tag https://github.com/oracle/graal/releases/tag/vm-21.2.0 results in:

```
Error retrieving https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-21.2-b08/labsjdk-ce-11.0.12+6-jvmci-21.2-b08-linux-amd64.tar.gz.sha1: HTTP Error 404: Not Found
```

**Comment by dougxc** [comment]
@marwan-hallaoui will take care of this.

**Comment by marwan-hallaoui** [comment]
Missing artifacts are pushed, @zakkak  could you please test if the issue is fixed ?

**Comment by marwan-hallaoui** [comment]
Missing artifacts are pushed, @zakkak could you please confirm that issue is fixed?

**Comment by zakkak** [comment]
Confirmed. Thank you @marwan-hallaoui!
