### ISSUE TITLE
Error building openjdk

### ISSUE THREAD

**Issue by starkgate** [graalvm/labs-openjdk-11#3]
I'm getting the following error when running `python build_labsjdk.py`.
```
Exception in thread "main": jdk.vm.ci.common.JVMCIError
jdk.vm.ci.common.JVMCIError: java.lang.ClassNotFoundException: org.graalvm.word.WordBase
```

Here is the entire log:
[log.txt](https://github.com/graalvm/labs-openjdk-11/files/4338659/log.txt)

**Comment by gradinac** [comment]
Hey starkgate!
I see you are using GraalVM EE as the Boot JDK to build the labsjdk. I'm not sure what could be causing the problem, but as a workaround, have you tried building it using one of the `labs-openjdk-11` releases? You can grab them from here: https://github.com/graalvm/labs-openjdk-11/releases
To instruct the build script to use the newly downloaded JDK:
`python build_labsjdk.py --boot-jdk <path to the root folder of the labs-openjdk-11 release>`

**Comment by starkgate** [comment]
I see there is finally a binary release of OpenJDK 11 and GraalVM 20.1.0, this solves my problem. I'm very grateful, thank you!
