### ISSUE TITLE
Cannot build LabsJDK CE 11 with GCC 10

### ISSUE THREAD

**Issue by YaSuenag** [graalvm/labs-openjdk-11#6]
I tried to build LabsJDK CE 11 on Fedora 32 which is installed GCC 10.1.1, but I saw some errors.  
In upstream (jdk/jdk) seems to be fixed them in [JDK-8235903](https://bugs.openjdk.java.net/browse/JDK-8235903).

It has three subtasks - [JDK-8238380](https://bugs.openjdk.java.net/browse/JDK-8238380), [JDK-8238386](https://bugs.openjdk.java.net/browse/JDK-8238386), [JDK-8238388](https://bugs.openjdk.java.net/browse/JDK-8238388). I want to backport them to LabsJDK.

**Comment by YaSuenag** [comment]
We also need #7 fix to complete building LabsJDK CE 11 on Fedora 32.

**Comment by dougxc** [comment]
Another option is to backport these issues to https://hg.openjdk.java.net/jdk-updates/jdk11u-dev/ since labsjdk-ce-11 merges in changes from there every 3 months.

**Comment by YaSuenag** [comment]
I agree with you to backport them to upstream jdk11u. Can you send backport requests?

Or we can also pass `-fcommon` to `CFLAGS` / `CPPFLAGS` as java-11-openjdk on Fedora 32: https://src.fedoraproject.org/rpms/java-11-openjdk/blob/a3184a2c71409cdf189e9d7ab3154c2a8458e657/f/java-11-openjdk.spec#_1469

**Comment by dougxc** [comment]
> Can you send backport requests?

I'll leave that up to the jdk-updates project. If you cannot submit the requests yourself, maybe @adinn can help.

**Comment by YaSuenag** [comment]
I've sent backport requests for them. I'll backport them to jdk-updates/jdk11u-dev if they are approved, then I will close this issue.

**Comment by dougxc** [comment]
Thanks!

**Comment by YaSuenag** [comment]
I've backported them, so I close this issue.

* https://bugs.openjdk.java.net/browse/JDK-8249792
* https://bugs.openjdk.java.net/browse/JDK-8249794
* https://bugs.openjdk.java.net/browse/JDK-8249795
